### ISSUE TITLE
Bulb test report (Don't know what to do from here to try test it out :/)

### ISSUE THREAD

**Issue by jazza1234567** [sbidy/wiz_light#116]
1. Made an UDP request with nc to the bulb:
echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 <YOU BULB IP> 38899
Report the output here:

{"method":"getSystemConfig","env":"pro","result":{"mac":"a8bb508e7154","homeId":2147443,"roomId":3232008,"moduleName":"ESP03_SHTW_31","fwVersion":"1.21.0","groupId":0,"drvConf":[20,1],"ewf":[255,0,255,204,0,0,0],"ewfHex":"ff00ffcc000000","ping":0}}

2. Provide the native features of the bulb:

Dimmer (yes/no): yes
Color Temp (yes/no): yes
Effects (yes/no): yes
RGB (yes/no): no

3. Tested?
No
If you found bug or problems with the bulb please open an new issue and add a reference to this one.

OPTIONAL

4. Prepare the YAML - replace <Name> with the ESP_XXXXXXXX name from step 1.

  ESP03_SHTW_31:
     name: ESP03_SHTW_31
     features:
       brightness: true
       color: false
       effect: true
       color_tmp: true
     kelvin_range:
       min: 3000
       max: 4000
       
       (kelvin range may be wrong)

**Comment by sbidy** [comment]
In the new 0.4 version the features of the bulb should be detected automatically from the integration.
Please test the new version from the `Releases` tap.

**Comment by jazza1234567** [comment]
> In the new 0.4 version the features of the bulb should be detected automatically from the integration.
> Please test the new version from the `Releases` tap.

Thanks for replying Stephen. Absolutely love how snappy and responsive the 9/11 Downlights i have working under your hard work. 

Fairly certain i have everything up to date but that being said this type of stuff is not a strong skill of mine, that being said it doesn't stop me trying to self teach. I've spent hours looking at every file in the resp, trying to do things with them etc. 

Ill have a look at my version when i am home in an hour and will report back if i resolve or not. 

Cheers for all the good work mate.

**Comment by jazza1234567** [comment]
@sbidy had a quick fiddle around before sleeping. Fairly sure i did upgrade my release, but still the best i can get is having a bulb appear as a device but not entity/ability to control
