### ISSUE TITLE
Specific RGBW

### ISSUE THREAD

**Issue by spencerthayer** [sbidy/wiz_light#120]
Is there a way to precisely control the color values? I cannot seem to figure it out in the documentation. If there isn't is this on the road map?

**Comment by sbidy** [comment]
You can control the values via HASS with RGB or mireds in automation or scripts. There are no specific presets of colors. With the RGB you can set up to 4.000.000.000 different possible colors. But at the end the type of the LEDs are different from bulb to bulb. It can be possible that the same color value looks different from bulb type to bulb type.
