### ISSUE TITLE
TV time effect not correct colour 

### ISSUE THREAD

**Issue by enrauk** [sbidy/wiz_light#123]
Switching to TV time effect in home assistant does not output the correct colour.  TV time is meant to be blue with a low brightness.  Selecting the effect through home assistant outputs a low brightness daylight white.

**Comment by andrew-engdahl** [comment]
I am having a similar issue when selecting the warm white effect. I also get the daylight white color temperature.

**Comment by sbidy** [comment]
It seems to be an issue with the Scene-ID in the light mode.

Can you please provide the full bulb type (ESP32-TWxx-xxx) via `nc`? Because it seems to be a bug in some bulb types.

**Comment by andrew-engdahl** [comment]
This is blub type ESP03_SHRGB1C_01 which for me is a BR30 E26 Color & Tunable White
