### ISSUE TITLE
HACS update fails

### ISSUE THREAD

**Issue by VerityNH** [sbidy/wiz_light#13]
When trying to update with HACS, get an error 
![image](https://user-images.githubusercontent.com/51718614/79292068-38bc0480-7e9e-11ea-9c33-666b95ee9415.png)

**Comment by danVnest** [comment]
HACS requires the custom_components directory as described and dealt with in pull request https://github.com/sbidy/wiz_light/pull/2.
This directory was removed for some reason in commit https://github.com/sbidy/wiz_light/commit/1d1e9cdfc706a1777632f1eef884ce545209e4f9.
@sbidy can you reimplement the required directory structure?

**Comment by danVnest** [comment]
By the way, this is also the official recommended custom component structure: https://github.com/custom-components/blueprint

**Comment by sbidy** [comment]
Please try the update again! Thanks.

**Comment by danVnest** [comment]
Directory is misspelled. Should be ‘custom_components’ instead of ‘custom-components’.

**Comment by sbidy** [comment]
oh man ... fixed 😃 . Thank you.

**Comment by VerityNH** [comment]
Works as expected,
Tested 

Thanks, guys
