### ISSUE TITLE
Implement use of Rhythms from WiZ App - Feature Request

### ISSUE THREAD

**Issue by 1activegeek** [sbidy/wiz_light#135]
=== WARNING: HUMBLE THANKS AHEAD ===
I'll start with a tremendous thank you for the work you've done thus far. I was able to without much fanfare, get my WiZ lights up and running inside of HA in a matter of about 30 minutes. I'm glad that a cheap bulb set like this could easily be integrated with HA - but still be produced by such a reputable company. Also really excited by the post you shared of the WiZ team sending you hardware to test and expand this integration.

==== ACTUAL "Issue" STARTS HERE =====

Now to the issue title - I'd like to submit an expansion of feature/capability if possible. Not knowing the inner workings of the communications coming between your integration, the WiZ app, and the devices - I'd love to see the implementation of the Rhythm functionality for these lights. When in the app, there is an option to quickly tap the "enabled" Rhythm from the control of any individual light, group, or room. For most of my home, I'd love this mechanism to control my lights, their temp, and brightness throughout the day. I know HASS has some integrations that might achieve this, but as far as I understand, this becomes something saved into the bulb itself so it can self correct at any point in the day and will ensure uniformity within all my bulbs.

I believe the Rhythm setups are just a glorified schedule, and thus are stored in bulb. Also, it would explain why you can only have one active, as they must limit the data stored in the on-board storage of the bulbs. 

Happy to help contribute anything that can help in determining how to get this into the integration.

**Comment by code-in-progress** [comment]
If you have the Rhythm defined in the app for the room, then you can use the `effect: 'Rhythm'` to activate it from HA in automations, scripts, and/or scenes.

![image](https://user-images.githubusercontent.com/33837776/114706732-5c0ad100-9cf7-11eb-80f2-7cecf3d4b0f4.png)

As of this moment, I don't think there is anyway to actually define Rhythms outside of the app though.

**Comment by 1activegeek** [comment]
Wow. Thank you @code-in-progress, I somehow clearly missed that in the list. I tried reading through the options to see if it was in that list thinking that would be the logical place. But that is in fact there, will close out this request as it's already supported! I wouldn't expect the ability to build/create these inside HASS.
