### ISSUE TITLE
The custom integration 'wiz_light' does not have a valid version key

### ISSUE THREAD

**Issue by wkruise** [sbidy/wiz_light#155]
After I updated my HA to the newest versions I noticed that my wiz lights weren't available anymore. When I checked my configuration I saw this error:

Platform error light.wiz_light - Integration 'wiz_light' not found.

So I decided to check if the integration still was available but I didn't see the custom_components folder anymore, so I decided to act like I would do a fresh install. But after I did that I keep getting below error when I check the core log and I'm scrambled about the reason.

2021-07-09 23:56:40 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'wiz_light' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

How to fix this issue?

**Comment by jcasarini** [comment]
Hi
I just checked mine, and it does have a valid version key.

This is my manifest.json:

`
{
  "version": "0.4.1",
  "domain": "wiz_light",
  "name": "WiZ Light",
  "config_flow": true,
  "documentation": "https://www.home-assistant.io/integrations/wiz_light",
  "requirements": [
    "pywizlight==0.4.6"
  ],
  "ssdp": [],
  "zeroconf": [],
  "homekit": {},
  "dependencies": [],
  "codeowners": [
    "@sbidy"
  ]
}
`

It's located at /config/custom_components/wiz_light/

Compare it with yours.

Hope it helps.

Joaquin

**Comment by wkruise** [comment]
Thanks Joaquin, I found my original wiz light integaration back in that folder. Clearly I didn't correctly analysing my problem and caused more problems with a 'fresh' installation. At the moment I'm reverting to the snapshot I made before I updated the system and will work from there again.

**Comment by wkruise** [comment]
Well, probably not solve totally in the correct way but it works again. Just deleted the "old" integration in the custom components folder and performed all steps to add it again. Error is gone and I can control my lights again.
