### ISSUE TITLE
ESP56_SHTW3_01 incorrect dynamic kelvin ranges

### ISSUE THREAD

**Issue by mo1seev** [sbidy/wiz_light#157]
ESP56_SHTW3_01 lamp have kelvin range is 2000k - 5500k. But auto discovery set min value - 2700k.

➜  ~ echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 192.168.1.52 38899
{"method":"getSystemConfig","env":"pro","result":{"mac":"a8bb50c5a200","homeId":1756465,"roomId":2614450,"rgn":"eu","moduleName":"ESP56_SHTW3_01","fwVersion":"1.23.0","groupId":0,"drvConf":[20,1],"ping":0}}%

**Comment by sbidy** [comment]
Ah that is an bug in the pywizlight lib.
https://github.com/sbidy/pywizlight/blob/341dc04775cf5c63c7c4bae3b49d36928bc00012/pywizlight/bulb.py#L317

**Comment by sbidy** [comment]
Fixed in pywizlight 0.4.12
