### ISSUE TITLE
FR: add attribute for MacID

### ISSUE THREAD

**Issue by johanjongsma** [sbidy/wiz_light#170]
Hi,

I'm connecting to my lights to IP, by finding the IP through the last six digits of the MAC-address. Could you please add an attribute for MacID, so that it could be add to the lights definition?

Like this:

- platform: wiz_light
  name: TOffice 4
  mac: 39eeba
  host: 192.168.2.128

No need to process it (for now) or do anything with it, please just as a 'comment' fields.

Thanks, Johan Jongsma

**Comment by sbidy** [comment]
I will add this for the next release that these digits will be a part of the bulb properties/info.

**Comment by sbidy** [comment]
Done - in the next version.
