### ISSUE TITLE
Not able to set effects for scene

### ISSUE THREAD

**Issue by kgknox27** [sbidy/wiz_light#177]
I'm having an issue where if I set a bulb to an effect within a scene it will not save that effect. This happens especially if the bulb was ever manually set to a color. 

Steps to reproduce: 
1. Create a scene. 
2. Add bulbs to the scene. 
3. Set the bulb to an effect. 
4. Save the scene and exit. 
5. Open the scene again. 
6. The effect bar will be empty and the bulb will be a manual color. 

I'm using a mix of  Philips 555623 recessed & Phillips color A19. Both share the issue. 

Thanks for all the hard work!

**Comment by sbidy** [comment]
Mh, I have to check that. 😄

**Comment by kgknox27** [comment]
Thanks! I’m happy to help or provide any info I am able.

**Comment by ClaireRovic** [comment]
I have the same/similar issue, created a light group with a unique_id (allowed me to edit in UI). When add to a scene it appears the brightness is the only value that can be saved, I then test a single light and had the same issue.

**Comment by orbazm** [comment]
Having the same issue on a new install using only Wiz lights: ESP01_SHRGB1C_31
Initial colour was red then:
- Created a scene where the effect was Party
- Light changes to Party effect and Icon stays Red
- Save the scene (without changing the light, so light is still Party)
- Activate the scene
- Light changes back to red

It's as if the effect parameter is ignored and only the basic colour commands are sent. 

From scenes.yaml:

- id: '1638439619588'
  name: Office Party
  entities:
    light.wiz5:
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 255
      hs_color:
      - 0
      - 100
      rgb_color:
      - 255
      - 0
      - 0
      xy_color:
      - 0.701
      - 0.299
      effect: Party
      friendly_name: Wiz5
      supported_features: 23
      state: 'on'

**Comment by orbazm** [comment]
Can confirm that removing all of the IP configured lights in the configuration.yaml and readding all lights via the Add Integration -> Wiz Light UI fixed this issue for me.

Thanks!

**Comment by bdraco** [comment]
This can be closed as its fixed in the core version
