### ISSUE TITLE
G25 filament bulb supported features

### ISSUE THREAD

**Issue by danVnest** [sbidy/wiz_light#18]
WiZ G25 filament bulbs (ESP56_SHTW3_01) support colour temperature and effects as well as brightness change.

Perhaps fix in light.py by changing
```
# Firlament bulbs support only dimmer
if self._bulbType == 'ESP56_SHTW3_01':
    _LOGGER.info("Found ESP56_SHTW3_01 bulb")
    return SUPPORT_BRIGHTNESS
```
to
```
# Filament bulbs support brightness and color temperature
if self._bulbType == 'ESP56_SHTW3_01':
    _LOGGER.info("Found ESP56_SHTW3_01 bulb")
    return SUPPORT_BRIGHTNESS | SUPPORT_COLOR_TEMP | SUPPORT_EFFECT
```

The above does work, however, these lights don't support all effects, only those in the screenshot below (these are those that don't change colour, only colour temperature). This would either require a list of effects for each different bulb type; or filtering the scenes by supported features.
![IMG_4936](https://user-images.githubusercontent.com/4771860/80169751-a2b87480-8629-11ea-848d-6a05c5aba7ec.png)

**Comment by sbidy** [comment]
Now supported with the correct features. Please test if all effects are available. I think I forgot the _Cozy_ ... 😄 
Note: I don't added the "warm white" and "cold white" effect. In my opinion this is no a real effect and can be controlled better in the HA automation.

Please test the new version an give me a feedback! 😃 
Thank you for the contribution!!

**Comment by danVnest** [comment]
Perfect, thank you!
