### ISSUE TITLE
Clarify the installation instructions

### ISSUE THREAD

**Issue by Hexis858** [sbidy/wiz_light#180]
Cheers @sbidy ,

Could you clarify the installation instructions steps. As a new HA user I had trouble accessing and finding 'custom_components' directory. "WiZ Light" integration will also not appear in the new integration list without clearing the browser cache.

After installing the WiZ integration is worked nicely. :)

Suggested installation instruction updates:

2. Go to the HA 'custom_components' directory within the HA installation path (The directory is in the folder where the 'configuration.yaml' file is located. If this is not available - create this directory).

7. Add the bulbs either by:
	- HA UI by navigating to "Integrations" -> "Add Integration" -> "WiZ Light" (If it is not available, clear your web browser cache to renew the integrations list.)

**Comment by ksignorini** [comment]
These definitely don't seem to be correct. Even after installing with HACS using the 3 dot menu and adding the repository web address (https://github.com/sbidy/wiz_light) and rebooting doesn't give any extra options in Add Integration in the main Configuration page.

Although the instructions seem to indicate that integration/bulbs can be added through the HA UI, I can't find a way to do it other than through editing the configuration.yaml file.

**Comment by ksignorini** [comment]
Actually, I can't seem to get them to show up through a manual edit, either.

**Comment by sbidy** [comment]
Updated - Thank you !
