### ISSUE TITLE
Too many "No bulb type can be detected - fall back to full feature" errors.

### ISSUE THREAD

**Issue by danVnest** [sbidy/wiz_light#19]
When starting up Home Assistant I get many of the below errors (more than once for each light).
```
2020-04-24 12:14:02 ERROR (MainThread) [custom_components.wiz_light.light] No bulb type can be detected - fall back to full feature
```
The lights do work properly afterwards, so I'm guessing Home Assistant is trying to get the `supported_features` property before `await self.get_bulb_type()` is complete in light.py.

Perhaps move the error message to `get_bulb_type()` so it only triggers once failed rather than also when uninitialised?

**Comment by sbidy** [comment]
fixed with last commit - removed the "error" because the light will be initialized after the async call was made.
