### ISSUE TITLE
Pastel colors after 0.4.3

### ISSUE THREAD

**Issue by martroy** [sbidy/wiz_light#200]
Hi,

After updating to 0.4.3, some colors seem to be limited to pastel hues, i.e., much less saturated than with the previous release. Rolling back to 0.4.2 fixes the problem. Note that some colors have the right saturation.

All of my lights are Wiz downlights (model 23009) with the latest firmware (1.24.0).

Here is a scene I am using to test this:
- id: '1637177700706'
  name: New Scene
  entities:
    light.wiz_zwift:
      min_mireds: 153
      max_mireds: 370
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 255
      hs_color:
      - 14.921
      - 100
      rgb_color:
      - 255
      - 63
      - 0
      xy_color:
      - 0.677
      - 0.319
      friendly_name: wiz_zwift
      supported_features: 23
      state: 'on'

The bulb should be orange-red but, with 0.4.3, it is more like a pale salmon color.

Let me know if you need more information.

**Comment by dfayne** [comment]
I am seeing a similar issue. I have my bulbs bridged to HomeKit via HASS Bridge. When setting the color to Red for example in Apple's Home App, the bulb changes to a pink-ish color. Blue comes us as a very pale blue. However, if I ask Siri to change the color to red it's fully saturated. I am no programmer so I have no clue if this is an issue with this integration or the HASS bridge but it did pop up after installed 0.4.3.

**Comment by martroy** [comment]
I did a bit more testing today. I've tried deleting all the bulbs and re-adding them using the integration UI but I am still getting the same behavior. What appears to happen is that for some colors, the picker will not let me select the full color that is on the outside ring. When setting it, it will always go back to a less saturated tone.

As an example, selecting the orange-red color shows the problem:
![wrong](https://user-images.githubusercontent.com/59968986/142519063-c6c537da-8869-4b23-a602-824d0857c5bf.png)

The red doesn't have the problem:
![right](https://user-images.githubusercontent.com/59968986/142519106-d4a74bf6-7a8c-401d-9be5-711043642183.png)

I am not sure but it looks like "pure" colors are fine but not the in between ones. Sometimes, when changing to one of the problematic hues, the light has the right color but slowly fades to a pastel tone.

**Comment by sbidy** [comment]
Yes, between these two releases, the library behind was changed. I have to check if there are values not correct set.
Because the color was calculated with the RGB (color) and CW (cold warm led) this can cause in a less saturated color.

**Comment by sbidy** [comment]
It seems to be an issue with the red channel only.

**Comment by martroy** [comment]
> It seems to be an issue with the red channel only.

Are you sure about that? I've just tested all of the colors and I am experiencing this with most of the colors except those that are "pure". Those with the green lines are ok. The red ones won't let me select the most saturated color.
![Screenshot 2021-12-12 151616](https://user-images.githubusercontent.com/59968986/145728121-572b2f45-c360-4279-9e48-d0bfdba85fe3.png)

**Comment by sbidy** [comment]
Yes, this "issue" comes from the computation of the saturation value. The library will add for this colors the white LED as saturation value. In the Wiz App you can switch between these two modes via Scenes, HASS doesn't have the possibility to add a kind of saturation slider.

**Comment by martroy** [comment]
Hi,

For HASS, I thought that the saturation was controlled by the color wheel, the outside ring being the most saturated? Isn't there a way to mimic 0.4.2 (pywizlight 0.4.12) behavior?

Here is a video to better illustrate what I mean:
https://user-images.githubusercontent.com/59968986/146394444-fbd9573b-10f8-44b5-a0a8-3a119ca8b392.mp4

You can see that, when clicking near the white circle for some of the colors, it drops back the saturation. The same behavior occurs with the bulb itself: the color is fully saturated for a fraction of a second then drops to the  less saturated color. Unfortunately, it is hard to show that in a video. 

One thing I've noticed is that the amount it drops back seems to follow a certain curve depending on how close the color is from one of the color that works. This would lead me to think that there is a problem when calculating one of the values. But, then again, I haven't looked at the code so I might be completely wrong on this...  

Thanks for you hard work btw!

**Comment by sbidy** [comment]
Fixed (hopefully) in Version 0.4.5 - please update

**Comment by martroy** [comment]
Yes, it works perfectly now. Thank you so much!
