### ISSUE TITLE
ESP03_SHRGB1W_01: Brightness slider not visible on Lovelace card

### ISSUE THREAD

**Issue by akx** [sbidy/wiz_light#208]
I have a small issue with a Lovelace dashboard for a ESP03_SHRGB1W_01 bulb: the circular brightness slider doesn't show up, even if it does appear on the "more info" popover for the bulb and works fine there.

![nobri](https://user-images.githubusercontent.com/58669/143779880-bdf87012-a389-4ddd-b31f-eaef618968b3.png)

Is this something I'm missing in the configuration?

The other bulbs are Zigbee Lightlink bulbs via zigbee2mqtt, if that helps with triaging.

**EDIT:** Curiously, the slider does show up for two other Wiz bulbs (ESP14_SHRGB1C_01).

ps. Thank you for a nicely working integration!

**Comment by sbidy** [comment]
Oh, that's strange, I don't recognized such an issue. So, please try to set up a debug for the integration (https://github.com/sbidy/wiz_light#enable-debug). Do you see any exceptions in the HASS log?

**Comment by bdraco** [comment]
This can be closed as its fixed in the core version
