### ISSUE TITLE
Wiz Recessed Downlight (Colour)

### ISSUE THREAD

**Issue by BenQuinlan** [sbidy/wiz_light#209]
### Discussed in https://github.com/sbidy/wiz_light/discussions/190

<div type='discussions-op-text'>

<sup>Originally posted by **BenQuinlan** October 21, 2021</sup>
I've been researching color LED recessed lighting to install and found this (amazing) HA integration. I wanted to ask if anyone has any experience using this with the Wiz Recessed Colour Downlights, and if there have been any issues? My use case would be to change the colour of all the recessed lighting via home assistant. </div>

**Comment by AaronVerDow** [comment]
Yes, I just added several today.  So far the work just like any other bulb in Home Assistant.
