### ISSUE TITLE
Can I integrate smart ceiling fans with this integration?

### ISSUE THREAD

**Issue by thanpolas** [sbidy/wiz_light#210]
I have found a big variety of smart ceiling fans from a company in Spain, “Faro Barcelona”. Their fans integrate with the WIZ application. One of their smart products is this: [DECO FAN Black/wood ceiling FAN LED with DC SMART motor](https://faro.es/en/collection/deco-fan-black-wood-ceiling-fan-led-with-dc-smart-motor/)

I am trying to figure out if I can integrate the fan to HomeAssistant, and through that to HK… I’ve found the WIZ integration on HASS, but it states that it supports only bulbs…

Will I be able to integrate this fan to HA and HK?

cross posted on HA forum: https://community.home-assistant.io/t/smart-ceiling-fan-using-wiz-app-integration/364664

**Comment by sbidy** [comment]
It is not planned from my side yet. There are some other devices which are supported by WiZ (Smart Plugs, Switches etc.).
But the current implementation to HASS is focusing on the bulbs.
If this is done and works as expected, a support for switches, bulbs or these fans is possible.

Maybe have a look into the pywizlight library. There you can find the baseline UDP functions for interaction with the WiZ platform.
