### ISSUE TITLE
No RGB controls for bulbs

### ISSUE THREAD

**Issue by tjkcc** [sbidy/wiz_light#212]
Hey! Many thanks for this integration. I'm On 0.4.4, added a few bulbs via UI, can't seem to find color controls anywhere. What I am doing wrong?

![image](https://user-images.githubusercontent.com/47875364/146435638-4f752d29-1920-485c-9207-5927f6b36b27.png)

The bulb is ESP01_SHRGB1C_31

**Comment by sbidy** [comment]
Should be shown up after you turn on the light.

**Comment by tjkcc** [comment]
You are right @sbidy , all it took is to turn it on 😅
Thanks

![image](https://user-images.githubusercontent.com/47875364/146442757-5186eb2f-ea57-4a1b-bdac-5354cc005cc6.png)

**Comment by sbidy** [comment]
You welcome 😄
