### ISSUE TITLE
Wiz Smart plugs detected as lights

### ISSUE THREAD

**Issue by RaptorPR443** [sbidy/wiz_light#214]
the Wiz smart plugs when you add them via the ui, it adds them as lights not as switches. since yaml is not longer supported it gives problem when you try to use alexa or google to turn them on or off. and in automations you need to call service as light turn on/off and not service switch turn on/off.

**Comment by sbidy** [comment]
Switches not supported “official” from this integration. The support to add WiZ Switches and Plugs are on the features list.

**Comment by Mick51** [comment]
> Switches not supported “official” from this integration. The support to add WiZ Switches and Plugs are on the features list. You can use the integration as "bulb" to switch on/off the plugs (as you mentioned).

When will there be official support for Smartplugs? Because in the Wiz application you may well declare it as a bulb or a socket, the problem comes from you not from the possibility of adding.

**Comment by Mick51** [comment]
> Switches not supported “official” from this integration. The support to add WiZ Switches and Plugs are on the features list. You can use the integration as "bulb" to switch on/off the plugs (as you mentioned).

If you ask you to turn off the lights, it's not for him to turn off the sockets........Me, that's a real problem for me. Before I had Smartplug and Bulbs entities now it's nonsense management level........Give us the possibility of being able to rename the entity. Thank you

**Comment by bdraco** [comment]
This can be closed as its implemented in the core version
