### ISSUE TITLE
DNS/No configuration.yml/No discovery - ETA

### ISSUE THREAD

**Issue by doug62** [sbidy/wiz_light#216]
May we have the ETA for autodiscovery? Due to; mDNS not working, no more support for configuration.yaml and manual configuration now, (and my shitty orbi changing IPs) - I really can't use the updates?  Is there an ETA for autodiscovery?  (mucho thanks for your good works thus far....)

**Comment by sbidy** [comment]
I'm working on it. The discovery itself is already implemented and working in the pywizlight library. The main problem is to bring this into the wiz integration for HASS. I'm looking forward to having something until Christmas.

Currently, I do a some bug fixes and improvements for the HASS core PR.

**Comment by sbidy** [comment]
I'm still working on it. In the https://github.com/sbidy/wiz_light/tree/discovery_test there is my current working state.
The bulbs will be discovered by UDP broadcast and you can select these in a list

Currently, only one per run can be added.

**Comment by bdraco** [comment]
This can be closed, discovery is implemented in the core version
