### ISSUE TITLE
YAML Config Support is no longer supported!. Please re-add the bulbs via the UI. ?

### ISSUE THREAD

**Issue by Guitarans** [sbidy/wiz_light#217]
Great with a update, 
im not trying to be rude, im just a noob.
But how do I "re-add the bulbs via the UI" ?

**Comment by quielb** [comment]
On Home Assistant go To:
Configuration->Integrations. On the bottom right hand corner there is a button to Add Integration. After clicking on that Search for "Wiz". Then you can add the integration. You will have to do that for each wiz light you want to control.

**Comment by Guitarans** [comment]
oh i see. how cool!!  Can i give a long distant beer or something, like a donation...?

**Comment by sbidy** [comment]
I'm still working on it. In the https://github.com/sbidy/wiz_light/tree/discovery_test there is my current working state.
The bulbs will be discovered by UDP broadcast and you can select these in a list

Currently, only one per run can be added.

**Comment by Fleshi1981** [comment]
> On Home Assistant go To: Configuration->Integrations. On the bottom right hand corner there is a button to Add Integration. After clicking on that Search for "Wiz". Then you can add the integration. You will have to do that for each wiz light you want to control.

Thanks I was also looking 😬🙂
