### ISSUE TITLE
Set effect in automation

### ISSUE THREAD

**Issue by lamebear** [sbidy/wiz_light#222]
Is there a way to set the effect of the light in an automation? For context, I am wanting to change the lights to Daylight at sun up and Warm White at sun down. When I go to use the device in an automation, the only options I have are: 

- Turn On
- Turn Off
- Toggle
- Increase Brightness
- Decrease Brightness

A scene will not work as I don't want to turn on the lights if they are off, I just want to change the effect.

**Comment by hugocib** [comment]
You can call an effect in automations through Call service > Light Turn on, and then on the last line there's an Effect text box.
