### ISSUE TITLE
Implemt some HA standards

### ISSUE THREAD

**Issue by sbidy** [sbidy/wiz_light#25]
https://developers.home-assistant.io/docs/entity_index/#generic-properties
 - Device ID
 - Unavailable

**Comment by ItsRhen** [comment]
Is the idea behind this issue that entities will register as devices as well? Would allow them to be added to Areas for group control. I really appreciate this integration.

**Comment by sbidy** [comment]
No, the integration is only planed for the light devices in HA.

**Comment by sbidy** [comment]
Maintained in the "core" branch of HA.
