### ISSUE TITLE
ESP15_SHTW1_01I - white only bulb - ha card displays color wheel

### ISSUE THREAD

**Issue by caesar1987sk** [sbidy/wiz_light#28]
I have white only Wiz bulbs - with possibility to set brightness and color temperature.
On home assistant card is displayed also color wheel. When i select any color on it, call to bulb return error.

{"method":"getSystemConfig","env":"pro","result":{"mac":"xxx","homeId":xxx,"roomId":xxx,"homeLock":false,"pairingLock":false,"typeId":0,"moduleName":"ESP15_SHTW1_01I","fwVersion":"1.18.3","groupId":0,"drvConf":[20,1]}}

Name of bulb from packaging is 
on side: WiZ A60 E27 WiZ60 TW F
in front WiZ A.E27 Led 810 lm EQ. 60W

Maybe there can be config for displaying color wheel, brightness and color temperature on hassio card. Default values should be all for all, then replaced by know bulbs features and then replaced by user config (when there is any).

After fix i can do test on my bulbs.

**Comment by sbidy** [comment]
I added the bulb to the list [Supported Bulbs](https://github.com/sbidy/wiz_light/blob/master/README.md#bulbs)

**Comment by caesar1987sk** [comment]
Color wheel is gone, thank you.
This bulb also supports scenes/efects. I am 95% sure that previously there was scene (?) dropdown/combobox, but currently its not on ha card.

**Comment by sbidy** [comment]
Can you please check with the official WiZ app what kind of effects are supported? I'm pretty sure that the bulb doesn't support all effects.
I'll add the bulb to the correct group to show the supported effects only.

**Comment by caesar1987sk** [comment]
Sure.
category White: Warm white, Daylight, Cool white, Night light
category Simple:  Cozy, Relax, Focus, TV time
category Progressive (30 min): Wake-up, Bedtime
category Dynamic: Candlelight, Pulse, Golden white, Steampunk

**Comment by sbidy** [comment]
ok, thank you. I'll update the bulb.

**Comment by sbidy** [comment]
Please clone the current version. The effects should be shown up in the UI.

**Comment by caesar1987sk** [comment]
its look like you didn't push commit.

**Comment by caesar1987sk** [comment]
effects are still not available, but after removing "ESP15_SHTW1_01I" from if on line 156:
```
if self._bulbtype == "ESP01_SHTW1C_31" or self._bulbtype == "ESP15_SHTW1_01I":
            return SUPPORT_BRIGHTNESS | SUPPORT_COLOR_TEMP
```
its working.

**Comment by sbidy** [comment]
Ah, this was an conflict in the commit. Now it should be fixed.

**Comment by caesar1987sk** [comment]
Thank you for adding my bulbs :) I am closing this issue.
