### ISSUE TITLE
getSystemConfig ESP05_SHRGBL_21 -- Wiz branded floodlights lights from Costco

### ISSUE THREAD

**Issue by avd706** [sbidy/wiz_light#34]
{"method":"getSystemConfig","env":"pro","result":{"mac":"a8bb50xxxxxxxx","homeId":364xxx,"roomId":570xxx,"homeLock":false,"pairingLock":false,"typeId":0,"moduleName":"ESP05_SHRGBL_21","fwVersion":"1.19.3","groupId":0,"drvConf":[30,1]}}

We can put these here? 

I can do on/off, brightness, temp, color, and effect. Steampunk works, not sure of rythm

**Comment by sbidy** [comment]
Update Readme
