### ISSUE TITLE
Homebridge?

### ISSUE THREAD

**Issue by kgrammatis** [sbidy/wiz_light#36]
Tremendous plugin! Is there any desire to port this to Homebridge?  Is anyone working on that?

**Comment by sbidy** [comment]
I've no information about that. Sorry. I'm not sure if you can use python libraries in Homebridge. If it is possible you can have look into the pywizlight repo here on GitHub. There you can find the implementation.

**Comment by code-in-progress** [comment]
> Tremendous plugin! Is there any desire to port this to Homebridge? Is anyone working on that?

There is a Homebridge plugin here: https://github.com/kpsuperplane/homebridge-wiz-lan

However, the author is stopping development on it and there are still some outstanding issues regarding discovery and mDNS calls.

You could just add a Homekit bridge from Home Assistant and then add your Wiz lights to Homekit that way.
