### ISSUE TITLE
Wiz smart plug test

### ISSUE THREAD

**Issue by jeffdeal** [sbidy/wiz_light#44]
**Please don't post bugs or issues here** This template is only for report a new bulb type for integration or successful test.

I have Wiz bulbs working successfully with your integration, so just for fun I bought a Wiz smart plug to try, model 9290024468.  I also noticed that there are new Wiz strip lights and motion detectors available.  

Provide the following information:

1. Made an UDP request with nc to the bulb:
`echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 <YOU BULB IP> 38899`
Report the output here:

I was unable to download nc - my browsers and Windows itself quarantined as malware.

2. Provide the native features of the bulb:
  
As this is only a smart plug, on/off is the only feature.

3. Tested?
    
I defined the device just like a bulb in my configuration.yaml file.  The device shows up and will successfully turn on!  Then the device icon will flip back to "off" but the switch remains on.  If I manually turn the switch off I can turn it on again from HA.  There are continuous errors in the log file regarding brightness and dimmer functions, which of course this device does not support.  But it seems the basics of operation with smart plugs is there and perhaps could be integrated relatively easily.  I really like my Wiz bulbs and integration with Home Assistant is greatly appreciated.  If I can help, I would be glad to do so.

**Comment by sbidy** [comment]
Thanks for the report. Yes that behavior can happen because of the mapping of an unknown device.
If you add such an unknown device all features will be mapped to this device. In case that his will not support dimmer/brightness will cause this exception.

But to map the correct features to the bulb I need the `nc` output.
Can you please try the  `echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 <YOU BULB IP> 38899` from an Linux device in the network?

**Comment by jeffdeal** [comment]
Here's the output:

{"method":"getSystemConfig","env":"pro","result":{"mac":"a8bb509b64de","homeId":616906,"roomId":2594939,"moduleName":"ESP10_SOCKET_06","fwVersion":"1.20.0","groupId":0,"drvConf":[20,2],"ewf":[255,0,255,255,0,0,0],"ewfHex":"ff00ffff000000"}}

Thanks!

Jeff



________________________________

**Comment by simora** [comment]
I have a working switch.py to implement the socket. I'll clean it up and submit a PR later today.

**Comment by simora** [comment]
#52

**Comment by jeffdeal** [comment]
I added your code to my config as a test - works great!

**Comment by sbidy** [comment]
I merged the pull to the code.
