### ISSUE TITLE
[Bulb Test Report] 

### ISSUE THREAD

**Issue by Rjaap** [sbidy/wiz_light#48]
**Please don't post bugs or issues here** This template is only for report a new bulb type for integration or successful test.

Provide the following information:

1. Made an UDP request with nc to the bulb:
`echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 <YOU BULB IP> 38899`
Report the output here:

{"method":"getSystemConfig","env":"pro","result":{"mac":"a8bb50cb2ba8","homeId":1601217,"roomId":2375858,"moduleName":"ESP03_SHRGB1C_01","fwVersion":"1.20.0","groupId":0,"drvConf":[60,1],"ewf":[200,255,150,255,0,0,40],"ewfHex":"c8ff96ff000028"}}

2. Provide the native features of the bulb:
  - Dimmer (yes/no): yes
  - Color Temp (yes/no): yes
  - Effects (yes/no): yes
  - RGB (yes/no): yes

3. Tested?
    yes/no
    If you found bug or problems with the bulb please open an new issue and add a reference to this one.
Yes. 

**Additional Info**
Add any other useful information about the bulb? Purchase link? Other stuff you want to share?

**Thank you for your support** We will integrate the bulb as soon as possible.

**Comment by Rjaap** [comment]
Additional info: https://www.wizconnected.com/nl-NL/consumenten/producten/8718699787059/

**Comment by sbidy** [comment]
Fixed with #51 in `bulbconfig` branch - merge to master will come after testing.
