### ISSUE TITLE
Could not set the right color temperature

### ISSUE THREAD

**Issue by Rjaap** [sbidy/wiz_light#50]
Referring to [Bulb Test Report] #48. 

The color range of this bulb is 2200K to 6500K. Home assistant only allows me to set a value between 2500K to 6500K.

**Comment by Rjaap** [comment]
Tried it, didn't work. Removed the integration, reinstalled it, didn't work either.

**Comment by ChrisLizon** [comment]
I'm noticing a similar behavior with the bulbs I have recently set up. see issue #56  

With the slider set all the way to "400" in home assistant, the bulb only tunes to 2500 according to the Wiz app. Setting the slider all the other way to "153" sets it correctly to 6500K. 

I am curious what the values inside home assistant actually reference, do they have any meaning?

**Comment by ahartmanns** [comment]
> I am curious what the values inside home assistant actually reference, do they have any meaning?

Home Assistant uses [mired](https://en.wikipedia.org/wiki/Mired) as the unit for colour temperature. `1000000 / mired = kelvin`, so 400 mireds is indeed exactly 2500 K.

**Comment by sbidy** [comment]
Thank you for the report - I'll try to implemented the different bulbs with the variations of Kelvin rages.

**Comment by sbidy** [comment]
Fixed with #51 in `bulbconfig` branch - merge to master will come after testing.
