### ISSUE TITLE
[Bulb Test Report] 

### ISSUE THREAD

**Issue by christophniederberger** [sbidy/wiz_light#53]
**Please don't post bugs or issues here** This template is only for report a new bulb type for integration or successful test.

Provide the following information:

1. Made an UDP request with nc to the bulb:
`echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 <YOU BULB IP> 38899`
Report the output here:

{"method":"getSystemConfig","env":"pro","result":{"mac":"a8bb5033318e","homeId":1707493,"roomId":2538449,"moduleName":"ESP03_SHRGBP_31","fwVersion":"1.20.0","groupId":0,"drvConf":[13,2],"ewf":[255,0,255,244,0,0,0],"ewfHex":"ff00fff4000000"}

2. Provide the native features of the bulb:
  - Dimmer (yes/no): yes
  - Color Temp (yes/no): yes
  - Effects (yes/no): yes
  - RGB (yes/no): yes

3. Tested?
What do you mean by "tested"? I installed the integration and added the light. I can just control on/off right now...  And after a while, the lamp is not reachable anymore. But that might be another issue since I just started...

**Additional Info**
Add any other useful information about the bulb? Purchase link? Other stuff you want to share?
Link: https://www.amazon.de/Trio-Leuchten-451850101-Sprachsteuerung-Fernbedienung/dp/B07Q95ZXN3

**Thank you for your support** We will integrate the bulb as soon as possible.

**Comment by sbidy** [comment]
Can you please confirm that only on/off works with the integration? All other features should also work by default.

**Comment by christophniederberger** [comment]
I only saw an on/off switch.
In the mean time, the entity shows up as „not available“ even though I didn’t change anything... and there’s nothing in the log.

i can still control the light from the Wiz app and even disconnected/reconnected the lamp and restarted the HA server...

PS: the integration didn‘t show up in HACS. Had to install manually...

________________________________

**Comment by christophniederberger** [comment]
I have to come back on this... The light works now like a charm. The error message was a misconfiguraiton on my side. And I can control all the features...

Thanks a lot for this awesome integration!
