### ISSUE TITLE
[Bulb Test Report] ESP03_SHRGB1C_01 - G95 globe E27 Color & Tunable White

### ISSUE THREAD

**Issue by ahartmanns** [sbidy/wiz_light#54]
**Please don't post bugs or issues here** This template is only for report a new bulb type for integration or successful test.

Provide the following information:

1. Made an UDP request with nc to the bulb:
`echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 <YOU BULB IP> 38899`
Report the output here:

`{"method":"getSystemConfig","env":"pro","result":{"mac":"a8bb50db0e51","homeId":1798722,"roomId":2680328,"moduleName":"ESP03_SHRGB1C_01","fwVersion":"1.20.0","groupId":0,"drvConf":[70,1],"ewf":[200,255,160,255,0,0,40],"ewfHex":"c8ffa0ff000028"}}`

2. Provide the native features of the bulb:
  - Dimmer (yes/no): yes
  - Color Temp (yes/no): yes
  - Effects (yes/no): yes
  - RGB (yes/no): yes

3. Tested?
    yes/no
    If you found bug or problems with the bulb please open an new issue and add a reference to this one.

Dimming, color temp, and rgb tested. I cannot set color temps lower than 2500 K via Home Assisstant although the bulb supports 2200K-6500K, and 2200K can be selected in the app. I think this is the same issue as #50. I tried changing "2500" to "2200" in the `max_mireds` function in `light.py` but it didn't fix the range.

**Additional Info**
Add any other useful information about the bulb? Purchase link? Other stuff you want to share?

ESP03_SHRGB1C_01 is currently listed twice in the table on the main page, once as "Philips Color &. Tunable-White A19" and once as "WiZ LED EAN 8718699787059". So I am basically reporting that ESP03_SHRGB1C_01 is _also_ the G95 color & white temp globe with EAN 8718699786359, see https://www.wizconnected.com/en/consumer/products/8718699786359/ (EAN on website and packaging match).

**Comment by sbidy** [comment]
Please clone the [bulbconfig Tree](https://github.com/sbidy/wiz_light/tree/bulbconfig).
It should be fixed with the `bulblibrary.yaml`

**Comment by sbidy** [comment]
Fixed with #51 in `bulbconfig` branch - merge to master will come after testing.
