### ISSUE TITLE
[Bulb Test Report] ESP03_SHRGB1W_01 - A67 bulb E27 Color & Tunable White

### ISSUE THREAD

**Issue by ahartmanns** [sbidy/wiz_light#55]
**Please don't post bugs or issues here** This template is only for report a new bulb type for integration or successful test.

Provide the following information:

1. Made an UDP request with nc to the bulb:
`echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 <YOU BULB IP> 38899`
Report the output here:

`{"method":"getSystemConfig","env":"pro","result":{"mac":"6c2990125e0e","homeId":1798722,"roomId":2680328,"moduleName":"ESP03_SHRGB1W_01","fwVersion":"1.20.0","groupId":0,"drvConf":[20,2],"ewf":[200,255,255,255,0,0,40],"ewfHex":"c8ffffff000028"}}`

2. Provide the native features of the bulb:
  - Dimmer (yes/no): yes
  - Color Temp (yes/no): yes
  - Effects (yes/no): yes
  - RGB (yes/no): yes

3. Tested?
    yes/no
    If you found bug or problems with the bulb please open an new issue and add a reference to this one.

Same as #54: tested everything except effects via Home Assistant, color temp range is incorrect (bulb supports 2200K-6500K, can only get 2500K-6500K via Home Assistant, see #50).

**Additional Info**
Add any other useful information about the bulb? Purchase link? Other stuff you want to share?

ESP03_SHRGB1W_01 is currently listed as "Philips Color &. Tunable-White A21" on the main page. I basically report here that it is _also_ the "A67 bulb E27 Color & Tunable White" with EAN 8718699786199, see https://www.wizconnected.com/en/consumer/products/8718699786199/ (EAN on packaging and website match).

**Comment by sbidy** [comment]
Please clone the [bulbconfig Tree](https://github.com/sbidy/wiz_light/tree/bulbconfig).
It should be fixed with the `bulblibrary.yaml`

**Comment by sbidy** [comment]
Fixed with #51 in `bulbconfig` branch - merge to master will come after testing.
