### ISSUE TITLE
[Bulb Test Report] ESP01_SHRGB1C_31 -  A19 Frosted Full Colour and Tunable White

### ISSUE THREAD

**Issue by ChrisLizon** [sbidy/wiz_light#56]
**Please don't post bugs or issues here** This template is only for report a new bulb type for integration or successful test.

Provide the following information:

1. Made an UDP request with nc to the bulb:
`echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 <YOU BULB IP> 38899`
Report the output here:

{"method":"getSystemConfig","env":"pro","result":{"mac":"a8bb50aec635","homeId":1995453,"roomId":2989331,"moduleName":"ESP01_SHRGB1C_31","fwVersion":"1.20.0","groupId":0,"drvConf":[33,1],"ewf":[255,250,150,255,0,0,40],"ewfHex":"fffa96ff000028"}}

2. Provide the native features of the bulb:
  - Dimmer (yes/no): YES
  - Color Temp (yes/no): YES
  - Effects (yes/no): YES
  - RGB (yes/no): YES

3. Tested?
    yes/no: YES
    If you found bug or problems with the bulb please open an new issue and add a reference to this one.

**Additional Info**
Add any other useful information about the bulb? Purchase link? Other stuff you want to share?

This modulename is already listed in the compatibility list, but the example was described as a recessed downlight. I'm not sure if this module name directly translates into a product line, but my bulbs are standard A19 sized. 

Purchased from Home Depot Canada

https://www.homedepot.ca/product/philips-wiz-60w-a19-frosted-full-colour-and-tunable-white-led-smart-home-wi-fi-light-bulb-2-pack-/1001421201

Bulb is labelled: 
c UL listed us
LED Lamp 3PM5

Wiz Colors line

800 Lumens
8.8W 2200-6500K (RGB) 100mA
120V~60Hz
Made in China 1K90
9290022656
Contains FCC ID: 
2AC7Z-ESPWROOM02D
Contains IC:
21098-ESPWROOM02D

**Thank you for your support** We will integrate the bulb as soon as possible.

Your integration is coming along pretty awesome! I bought these bulbs because they were ESP based and I intended to flash Tasmota, but I may just leave them as Wiz!

**Comment by sbidy** [comment]
Please pull the [bulbconfig Tree](https://github.com/sbidy/wiz_light/tree/bulbconfig).
It should be fixed with the `bulblibrary.yaml`

**Comment by sbidy** [comment]
Fixed with #51 in `bulbconfig` branch - merge to master will come after testing.
