### ISSUE TITLE
RuntimeWarning with switch configuration

### ISSUE THREAD

**Issue by RobinCutshaw** [sbidy/wiz_light#57]
Pulled the latest updates and switched from light to switch in the configuration.  Running HA from dev branch.  Received:

> /home/robin/github/core/config/custom_components/wiz_light/switch.py:43: RuntimeWarning: coroutine 'WizPlug.async_update' was never awaited
  self.async_update()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by sbidy** [comment]
Ok, thank you for the bug report.  Unfortunately I  don't have one of these Plugs to test this in real.
