### ISSUE TITLE
[Bulb Test Report] 

### ISSUE THREAD

**Issue by tgregory86** [sbidy/wiz_light#59]
**Please don't post bugs or issues here** This template is only for report a new bulb type for integration or successful test.

Provide the following information:

1. Made an UDP request with nc to the bulb:
`echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 <YOU BULB IP> 38899`
Report the output here:
{"method":"getSystemConfig","env":"pro","result":{"mac":"xxxxx","homeId":1542531,"roomId":2370700,"moduleName":"ESP03_SHRGB3_01ABI","fwVersion":"1.20.65","groupId":0,"drvConf":[80,2],"ewf":[255,0,255,255,0,0,0],"ewfHex":"ff00ffff000000"}}

2. Provide the native features of the bulb:
  - Dimmer (yes/no): Yes
  - Color Temp (yes/no): Yes
  - Effects (yes/no): Yes
  - RGB (yes/no): Yes

3. Tested?
    yes/no
    If you found bug or problems with the bulb please open an new issue and add a reference to this one.
Yes - no issues found yet. 

**Additional Info**
Add any other useful information about the bulb? Purchase link? Other stuff you want to share?

**Thank you for your support** We will integrate the bulb as soon as possible.

**Comment by sbidy** [comment]
Thanks !
