### ISSUE TITLE
[Bulb Test Report] 

### ISSUE THREAD

**Issue by meyerrj** [sbidy/wiz_light#63]
**Please don't post bugs or issues here** This template is only for report a new bulb type for integration or successful test.

Provide the following information:

1. Made an UDP request with nc to the bulb:
`echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 <YOU BULB IP> 38899`
Report the output here:

```
{"method":"getSystemConfig","env":"pro","result":{"mac":"a8bb50c7c741","homeId":724525,"roomId":1439578,"moduleName":"ESP01_SHRGB1C_31","fwVersion":"1.21.0","groupId":0,"drvConf":[33,1],"ewf":[255,250,150,255,0,0,40],"ewfHex":"fffa96ff000028","ping":0}
```

2. Provide the native features of the bulb:
  - Dimmer (yes/no): **YES**
  - Color Temp (yes/no): **YES**
  - Effects (yes/no): **YES**
  - RGB (yes/no): **YES**

3. Tested?
    **Yes**

**Additional Info**
Bought from Home Depot, WiZ WiFi Color tuning bulbs.  

Model ID:  23007

**Comment by ChrisLizon** [comment]
@meyerrj have you tried pulling the bulbconfig branch yet? That bulb should already be included in the bulbconfig.yaml and once you switch to that branch you should be able to set the bulb to 2200K. I don't know if it the branch would have any fixes for your other issue.
