### ISSUE TITLE
Cannot add repository to HACS

### ISSUE THREAD

**Issue by JanHG** [sbidy/wiz_light#81]
The Integration has disappeared from my HACS overview and when trying to add the repository again I get the following error:
'Repostitory structure for 2021.1.1 is not compliant'

**Comment by sbidy** [comment]
That is possible 😉 but the integration will come directly in the HASS core as integration. https://github.com/home-assistant/core/pull/44779

**Comment by bram-pkg** [comment]
Any updates on this?
