### ISSUE TITLE
Gauss Filament lamps

### ISSUE THREAD

**Issue by mo1seev** [sbidy/wiz_light#87]
Hello! There is a popular lamp manufacturer in Russia - Gauss. Recently, they have released a line of smart lamps: https://gauss.ru/smartlight/products/
Some of these lamps correspond to the models you support. But there is a filament model that works on a different platform: https://gauss.ru/item/umnaya-lampa-filament-1310112/ and https://gauss.ru/item/umnaya-lampa-filament-1280112/
I would like to ask you to add them to your plugin.

mo1seev-osx:~ mo1seev$ echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 192.168.1.51 38899
{"method":"getSystemConfig","env":"pro","result":{"mac":"a8bb50c5aaee","homeId":1756465,"roomId":2614450,"moduleName":"ESP56_SHTW3_01","fwVersion":"1.21.2","groupId":0,"drvConf":[20,1],"ewf":[255,0,159,255,0,0,34],"ewfHex":"ff009fff000022","ping":0}}

YAML:
ESP56_SHTW3_01:
  name: ESP56_SHTW3_01
  features:
    brightness: true
    color: false
    effect: true
    color_tmp: true
  kelvin_range:
    min: 2000
    max: 5500

**Comment by sbidy** [comment]
In 0.4. the detection should be done automatically.

**Comment by mo1seev** [comment]
Hi Stephan! In the 0.4.2 same lamp ESP56_SHTW3_01 have wrong temperature range. Autodetect is 2700k - 5500k. But right range is 2000k - 5500k.
